#pragma once
#include <stdbool.h>

void test_set_file(void);
void test_set_rank(void);
bool test_set_square(void);
void test_new_square_relation_direct(void);
void test_square_relation(void);
void test_opposite_color(void);
void test_inverse(void);
void test_piece_to_piecetype(void);
void test_piece_to_color(void);
void test_piecetype_to_piece(void);
void test_is_jump(void);
void test_rank_usi_string(void);
void test_file_usi_string(void);
void test_square_usi_string(void);
void test_square_inverse(void);
void test_file_inverse(void);
void test_rank_inverse(void);
void test_can_promote(void);
void test_set_board(void);
void test_print_board(void);
