#pragma once
#include "../shogi/bitboard.h"
#include "../shogi/position.h"

void test_new_set_mask_bb(bitboard bb);
void test_new_file_mask();
void test_new_rank_mask();
void test_new_all_one_bb();
void test_new_in_front_mask();
void test_new_enemy_field();
void test_set_biton();
void test_set_board();
void test_first_one_from();
void test_lance_block_mask();
void test_index_to_occupied();
void test_lance_attack_calc();
void test_new_lance_attack();
void test_byte_reverse();
void test_unpack();
void test_decrement();
void test_new_rook_attacks();
void test_rook_attack_rank();
void test_rook_attack_file();
void test_rook_attack();
void test_new_bishop_attacks();
void test_unpack256();
void test_decrement256();
void test_byte_reverse256();
void test_merge256();
void test_bishop_attack();
void test_new_king_attacks();
void test_new_gold_attacks();
void test_new_silver_attacks();
void test_first_one_from_nodelete();
void test_star_attacks();
void test_new_knight_attacks();
void test_new_pawn_attacks();